version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "8081:8081" # Suposing Vue.js app runs on 8081, change if needed
    volumes:
      - ./frontend:/app
      - /app/node_modules # Avoids overriding node_modules by local volume

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: personalfinancedb

volumes:
  postgres_data:
